# Generated by Django 4.0.5 on 2022-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=70)),
                ('event_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=70)),
                ('win_count', models.IntegerField()),
                ('race_count', models.IntegerField()),
                ('stat_str', models.IntegerField()),
                ('stat_end', models.IntegerField()),
                ('stat_con', models.IntegerField()),
            ],
        ),
    ]
